lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
profile: true

title: 赵星的个人博客
logo: /images/avatar.jpg
description: 
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal