lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
# kramdown:
markdown: GEM
highlighter: rouge
profile: true

title: 赵星的个人博客
logo: /images/avatar.jpg
description: 
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
# sass:
#   sass_dir: /assets/css/style.scss